sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install: pip install tox-travis tox
script: tox
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    tags: true
